### ISSUE TITLE
ERD 설계

### ISSUE THREAD

**Issue by lsh2613** [Young-Flow/server#1]
### 💬 Describe

본격 개발 전에 각자 ERD 설계 후 의견을 나누고 통합하기

### 📌 Tasks

ERD 설계 및 공유

**Comment by lsh2613** [comment]
https://www.erdcloud.com/d/AouMXa52Zyk4fjt7H

**Comment by jeongmallro** [comment]
https://www.erdcloud.com/d/DAq3KEh3af4WNeRya

**Comment by lsh2613** [comment]
### v1 24.12.24
![image](https://github.com/user-attachments/assets/e6c0aa39-00b8-4889-bdff-48871372ea5f)
