### ISSUE TITLE
브랜치 전략 논의

### ISSUE THREAD

**Issue by lsh2613** [Young-Flow/server#2]
## 논의 내용
issue, pr 템플릿 올리느라 master, dev 브랜치는 만들어두긴 했는데 어떻게 브랜치를 관리할지 아직 정하지 않은 것 같아서 브랜치 전략에 대해 논의하고자 이슈 생성했습니다

### GitFlow
![image](https://github.com/user-attachments/assets/3bb976b4-f3c1-4398-a15a-d4eab316a243)

### GitHubFlow
![image](https://github.com/user-attachments/assets/4bcc9995-1a28-4254-b28c-6e9007720744)

## 제안
일경험 3기 프로젝트 기간동안에는 1차 프로토타입만을 개발하고 이후에 더 고도화하는 작업을 염두해 둔다면 릴리즈 관리에 용이한 GitFlow가 적합하지 않을까 생각합니다
다만 QA를 진행하진 않으니 release 브랜치는 생략하고 master, dev, feat, hotfix 정도로 관리하면 어떨까요?

### 📌 Tasks

Git Flow vs GitHub Flow 정하기

**Comment by jeongmallro** [comment]
넵 저도 동의합니다. 말씀하신 대로 진행하시죠!
