### ISSUE TITLE
API 분리 기준 선정

### ISSUE THREAD

**Issue by lsh2613** [Young-Flow/server#25]
### 💬 Describe

BM 디테일 API를 조회하던 중 여러 도메인이 많이 섞여 있어서 어디까지 분리하는 것이 맞을지 고민 중에 있습니다. 
여러 도메인에 대해 역할을 나눠서 진행하고 있다 보니 개인적으로 정할 수 없을 것 같아 공유드립니다

다른 API에서도 여러 도메인이 섞여있을 수 있지만 BM 디테일 페이지에 대해서만 본다면 bm 정보, sp 정보(spURL), investment 정보(총 투자 금액, 투자자 명수), pt 정보(ptImg...), comment 정보 등이 있습니다

이 정보를 bm detail api에 대해 모두 조회하게 할 것인지, 각각 도메인 별로 따로 호출해서 사용할 수 있게 분리할 것인지를 논의해보면 좋을 것 같아요.

제 입장은 어차피 bm 기준으로 1:n인 여러 도메인에 대해서 한 번에 fetchjoin이 불가능 하고 댓글 처럼 데이터가 많이 쌓일 수 있는 도메인을 같이 조회하는 것은 추후 성능 이슈가 생겼을 때 골치아파질 수도 있을 것 같다는 이유로 1:1인 sp 정보만 포함시키는 것이 좋다는 의견입니다

### 📌 Tasks

API 분리 기준 선정

**Comment by jeongmallro** [comment]
넵 저도 데이터가 많아질 수 있는 investment나 comment는 특히 분리해야 한다고 생각합니다. 저희가 숏폼 페이지에서도 다양한 데이터를 전달해줘야 하기 때문에 한번의 api에 여러 데이터를 묶어서 가져오는 것보다 데이터 별로 api를 분리하는 게 맞다고 생각합니다. 어차피 sp나 bm은 항상 묶여서 조회될 것이기 때문에 승헌님 말씀하신 대로 진행하면 될 것 같습니다!

찾아보다가 저희랑 비슷한 내용의 토론을 발견해서 공유드려요 ㅎㅎ
https://okky.kr/articles/795157

**Comment by lsh2613** [comment]
흠 그럼 태그는 어떻게 할까요? 태그 자체는 많아질 것 같지 않은데 만약 다른 도메인 (아마 member나 sp)에서 사용 가능성을 염두해 둔다면 분리하는 것도 괜찮아 보이는데 어때 보이시나요?

**Comment by lsh2613** [comment]
아직 태그의 활용성에 대하여 기획이 마무리되지 않은 상황에서 이걸 정하는 것은 무의미해 보이네요. 
우선은 태그 api도 분리해두고 개발하겠습니다 추후에 다시 고민해보시죠!
