### ISSUE TITLE
SP pk id를 BM -> Long 제안

### ISSUE THREAD

**Issue by lsh2613** [Young-Flow/server#29]
### 💬 Describe

**현재 Sp Entity**
현재 sp의 pk는 연관관계 Bm에 대하여 @Id를 설정해놨습니다
``` java
@Entity
public class Sp extends BaseEntity {
    @Id
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "bm_id", nullable = false)
    private Bm bm;
}
```

**문제점 1**
> 기본키 매핑 불가능

다음과 같이 repository를 만들기 전에 엔티티만 만들어두고 실행 시 테이블과 pk가 정상적으로 생성됩니다
```java
public interface SpRepository extends JpaRepository<Sp, Bm> {}
```
``` java
// log
create table sp (views integer not null, bm_id bigint not null, created_at datetime(6), updated_at datetime(6), description varchar(255) not null, short_pitchurl varchar(255) not null, thumbnail_img varchar(255) not null, primary key (bm_id)) engine=InnoDB
alter table sp add constraint FKtcwy7h98tni958q9pnnktiqvg foreign key (bm_id) references bm (bm_id)
```

하지만 SpRepository를 만들면 다음과 같이 Sp의 IdClass를 인식하지 못하는 에러가 발생합니다
```java
Caused by: java.lang.IllegalArgumentException: This class [class com.pitchain.entity.Sp] does not define an IdClass
```

직접 docs를 찾아보진 않았지만 에러 원인에 대해 추측해봤을 때
@Id를 설정해둔 데이터를 관리하기 위해 @GeneratedValue를 사용하는데. 디폴트로 IDENTITY 전략을 사용하여 DB에 위임합니다.
MySQL의 경우 db내의 auto_increment를 사용하여 1씩 증가시켜주지만 현재 @Id가 붙은 데이터는 기본 자료형이 아닌 BM 객체 타입으로 설정되어 있어서 pk를 정상적으로 인식하지 못하는 것 같습니다
따라서 SpRepository extends JpaRepository를 통해 기본적으로 jpql을 생성할 때 id를 인식하지 못해 발생하는 에러 같습니다

다른 전략을 사용해서 해결할 수도 있겠지만 우선 기본키와 연관관계를 같이 관리하는 것 자체가 문제라고 생각합니다

**문제점 2**
> RESTFul 하지 않은 api endpoint
sp의 pk가 bm_id이기 때문에 sp detail 조회 api의 endpoint가 /sps/{bmId}로 관리된다
sp 자원에 접근하기 위한 id값이 bmId로 다소 모호한 의미를 가진다

**제안**
pk를 Long id로 설정하여 대체키를 관리하는 것이 효율적일 것 같아요

### 📌 Tasks

Sp Entity의 ID 관리 방안 논의

**Comment by jeongmallro** [comment]
아 저도 지금 댓글 API 개발하면서 이 에러를 발견했는데요,
다른 테이블의 기본 키를 가져와서 기본 키로 매핑할 때 아래와 같은 코드가 필요했었습니다.

``` java
    @Id
    @Column(name = "bm_id")
    private Long bmId;

    @OneToOne(fetch = FetchType.LAZY)
    @PrimaryKeyJoinColumn()
    private Bm bm;
```
근데 다시 생각해보니 일대일 관계로 매핑되어도 숏폼은 BM과 따로 관리될 필요성도 있을 것 같고, 기본 키에 의미를 부여한다는 점에서 적절하지 못한 것 같습니다. 

말씀하신 대로 대체 키를 넣는 게 좋다고 생각합니다. (대체 키의 중요성을 뼈저리게 경험하네요...)

**Comment by lsh2613** [comment]
저도 습관처럼 사용했던 건데 pk를 위해 컬럼 하나 만들어주는 게 개발/관리 측면에서 엄청나게 좋다는 걸 다시 깨닫습니다...
우선 말씀드린대로 대체키로 진행하겠습니다
```java
public class Sp extends BaseEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "sp_id")
    private Long id;

    ...
```
